Ecomm/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='/backend/login/', permanent=False)),
    # path('backend/login/', login_view, name='backend/login'),

    path('admin/', admin.site.urls),
    path('', include('ecomApp.urls')),
    path('', include('backendlogin.urls')),
    path('', include('registration.urls')),
    path('', include('menu_management.urls')),
    path('', include('advertisement_management.urls')),
    path('', include('banner_management.urls')),
    path('', include('order.urls')),
    path('', include('walet.urls')),
    path('', include('cart.urls')),
    path('', include('report.urls')),
    path('', include('notification.urls')),
    path('', include('chart.urls')),
    path('', include('influencer.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from .views import *
from django.urls import path
from .views import *

urlpatterns = [
    path('api/add_to_cart/', AddToCartAPIView.as_view(), name='add_to_cart'),
    path('api/get_cart/', CartDetailsAPIView.as_view(), name='get_cart'),
    path('api/get_all_coupon/', GetAllCouponAPIView.as_view(), name='get_all_coupon'),
    path("api/apply-coupon/", ApplyCouponAPIView.as_view(), name="apply_coupon"),


    path('api/get_cart/main/', CartDetailsMainAPIView.as_view(), name='get_cart'),

    path('api/increase/', IncreaseQuantity.as_view(), name='increase'),
    path('api/decrease/', DecreaseQuantity.as_view(), name='decrease'),

    path('api/increase/main/', IncreaseQuantityMain.as_view(), name=''),
    path('api/decrease/main/', DecreaseQuantityMain.as_view(), name=''),


    path('api/remove-cart-item/', RemoveCartItem.as_view(), name='remove_cart_item'),
    path('api/get_total_price/', CartTotalPrice.as_view(), name='CartTotalPrice'),

    path('api/send_coupon/', send_coupon, name='send_coupon'),
    path('api/unique-product-count/', UniqueProductCount.as_view(), name='unique_product_count'),
    
    path('api/wishlist/', WishlistAPIView.as_view(), name='wishlist')

]

chart/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    path('backend/daywise-chart/', daywise_chart, name='daywise_chart'),
    path('backend/render_product_dropdown/', render_product_dropdown, name='render_product_dropdown'),
    path('backend/itemwise-chart/', itemwise_chart, name='itemwise_chart'),
    path('backend/daily_chart/', daily_chart, name='daily_chart'),
    path('backend/category_wise_sales_chart/', category_wise_sales_chart, name='category_wise_sales_chart'),
    path('backend/profit_chart/', profit_chart, name='profit_chart'),

]

order/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('backend/orderapp/', orderlist, name="orderapp"),
    path('backend/confirmorderapp/', confirmorderlist, name="confirmorderapp"),
    path('backend/orderapp/view_item/<str:myid>/', view_item, name="orderapp/view_item"),
    # path('api/order/<int:pk>/', OrderList.as_view(), name='order-detail'),
    path('api/order/', OrderView.as_view(), name='user-order'),
    path('backend/orderapp/activate_catagory/<int:catagory_id>/', activate_catagory,name='orderapp/activate_catagory'),
    path('backend/orderapp/deactivate_catagory/<int:catagory_id>/', deactivate_catagory,name='orderapp/deactivate_catagory'),
    path('backend/orderapp/suspend_user/<int:catagory_id>/', suspend_user, name='orderapp/suspend_user'),
    path('backend/orderapp/deliver/<int:catagory_id>/', deliver, name='orderapp/deliver'),
    path('backend/orderapp/cancel/<int:catagory_id>/', cancel, name='orderapp/cancel'),
    # path('backend/orderapp/returnrequest/<int:catagory_id>/', returnrequest, name='orderapp/returnrequest'),
    # path('backend/orderapp/returnaccepted/<int:catagory_id>/', returnaccepted, name='orderapp/returnaccepted'),
    path('update_status/<int:id>/', update_status, name='newupdate_status'),

    path('api/create_order/', create_order, name='create_order'),
    path('api/verify_payment/', verify_payment, name='verify_payment'),
    path('api/orders/', OrderListAPIView.as_view(), name='grouped-order-list'),
    path('api/invoice/', OrderDetailsAPIView.as_view(), name='grouped-order-list'),

    path('api/generate_invoice/', generate_invoice, name='generate_invoice'),

    path('api/payment-options/', PaymentOptionListCreateView.as_view()),

    path('api/order/<str:order_id>/invoice/', DownloadOrderInvoice.as_view(), name='order_invoice'),

    path('api/create-qr-order/', create_qr_order, name='create_qr_order'),
    path('api/verify-qr-order/', verify_qr_order, name='verify_qr_order'),

    path('api/delivery-slots/', DeliverySlotListAPIView.as_view(), name='delivery_slots_list'),
    # ... other URLs
]

chart/models.py
from django.db import models

# Create your models here.

ecomApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.shortcuts import reverse
from django.utils import timezone
from decimal import Decimal
import random
from django.contrib.auth.models import User
from django.conf import settings
from menu_management.models import Item

class CustomUserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, name=None, referral_code=None, **extra_fields):
        if not phone_number:
            raise ValueError('The phone number field must be set')
        user = self.model(phone_number=phone_number, name=name, referral_code=referral_code, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone_number, password=None, name=None, referral_code=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(phone_number, password, name, referral_code, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    id= models.AutoField(primary_key=True)
    otp_value = models.CharField(max_length=6, blank=True)
    is_influencer = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=15, unique=True)  # You can adjust the max_length as needed.
    name = models.CharField(max_length=255,null=True)
    influencer_code = models.CharField(max_length=255,null=True)

    registration_id = models.CharField(max_length=255,null=True)
    # otp=models.CharField(max_length=6,null=True)
    bio=models.CharField(max_length=255,default='')
    profile_photo=models.ImageField(upload_to='videos/', null=True, blank=True)
    referral_code = models.CharField(max_length=10, blank=True, null=True)
    refer_by = models.CharField(max_length=10, blank=True, null=True)
    # password = models.CharField(max_length=128)  # Store the password as a hash.
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_date=models.DateField(auto_now_add=True)
    blocked_users = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='users_blocked_by')
    status = models.IntegerField(default=1)
    walet=models.FloatField(default=11)
    email = models.EmailField()
    # referral_link = models.CharField(max_length=255, blank=True, null=True, unique=True)
    # slug = models.CharField(max_length=15, blank=True,unique=True, null=True)
    objects = CustomUserManager()
    # total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    level = models.PositiveIntegerField(default=1)
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []
    # def save(self, *args, **kwargs):
    #     if not self.walet:
    #         self.walet = 11.0
    #     super().save(*args, **kwargs)
    def __str__(self):
        return f"{self.id}"


    #
    #
    #     super(CustomUser, self).save(*args, **kwargs)
    #     super().save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return True  # Custom implementation if needed

    def has_module_perms(self, app_label):
        return True  # Custom implementation if needed

    class Meta:
        ordering = ['phone_number']  # Adjust ordering field

class Otp(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
    email_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, blank=True)
    otp_created_at = models.DateTimeField(null=True, blank=True)
    phone_number=models.CharField(max_length=20, blank=True)

class Catagory(models.Model):
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')
    status= models.BooleanField(default=True)
    # uploaded_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.BigAutoField(primary_key=True)

    name= models.CharField(max_length=100)
    cat_name = models.ForeignKey(Catagory,on_delete=models.CASCADE)
    price=models.IntegerField()
    coupon = models.IntegerField( blank=True, null=True)
    description=models.CharField(max_length=500)
    image = models.ImageField(upload_to='images/')
    status= models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    barcode = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name


class CustomerCoupon(models.Model):
    id = models.AutoField(primary_key=True)
    coupon =  models.CharField(max_length=255, null=True)
    occasion = models.CharField(max_length=255, null=True)
    image = models.ImageField(upload_to='images/', null=True)
    start_date = models.DateField()
    expire_date = models.DateField()
    coupon_value = models.CharField(max_length=255, null=True)
    coupon_type = models.CharField(max_length=20, null=True)
    minimum_purchase = models.CharField(max_length=20, null=True)
    description = models.TextField(null=True)
    max_amount_discount = models.IntegerField(default=0)
    status= models.BooleanField(default=True)


class DeliveryCharge(models.Model):
    id = models.AutoField(primary_key=True)
    charge =  models.IntegerField()
    status= models.BooleanField(default=True)

class Stock(models.Model):
    id = models.BigAutoField(primary_key=True)
    openingstock=models.IntegerField(default=0)
    item_id=models.ForeignKey(Item,on_delete=models.CASCADE)
  #  pro_id= models.ForeignKey(Product, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

influencer/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Group, Permission
from order.models import Order
# from django.core.validators import UnicodeUsernameValidator
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from ecomApp.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator

class InfluencerManager(BaseUserManager):
    def create_user(self, email, phone, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, phone, password, **extra_fields)

class Influencer(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=255)
    otp_value = models.CharField(max_length=6, blank=True)
    passbook = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, unique=True, validators=[UnicodeUsernameValidator()])
    password = models.CharField(max_length=128)
    address = models.TextField()
    type = models.CharField(max_length=10)
    otp = models.CharField(max_length=10,null=True)
    commission = models.DecimalField(max_digits=10, decimal_places=2)
    code = models.CharField(max_length=50, unique=True)
    status = models.BooleanField(default=True)
    is_influencer = models.BooleanField(default=True)
    created_date=models.DateField(auto_now_add=True)

    # Required fields for AbstractBaseUser
    last_login = models.DateTimeField(default=timezone.now)

    objects = InfluencerManager()

    USERNAME_FIELD = 'phone'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

    def __str__(self):
        return self.name

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    @property
    def is_staff(self):
        return self.is_superuser

    # @property
    # def is_superuser(self):
    #     return self.status and self.is_staff

    @property
    def is_active(self):
        return self.status

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    class Meta:
        verbose_name = 'Influencer'
        verbose_name_plural = 'Influencers'

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        related_name='influencer_groups',  # Adjust related_name to resolve clash
        related_query_name='influencer_group',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        related_name='influencer_user_permissions',  # Adjust related_name to resolve clash
        related_query_name='influencer_user_permission',
    )


class InfluencerOtp(models.Model):
    # user = models.ForeignKey(Influencer, on_delete=models.CASCADE,null=True)
    user = models.ForeignKey(Influencer, on_delete=models.CASCADE)

    email_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=6, blank=True)
    otp_created_at = models.DateTimeField(null=True, blank=True)
    phone_number=models.CharField(max_length=20, blank=True)

class InfluencerAmount(models.Model):
    influencer = models.ForeignKey(Influencer, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(auto_now_add=True)

@receiver(pre_save, sender=Order)
def track_payment_id_change(sender, instance, **kwargs):
    if instance.pk:
        try:
            previous = Order.objects.get(pk=instance.pk)
            instance._previous_payment_id = previous.payment_id
        except Order.DoesNotExist:
            instance._previous_payment_id = None
    else:
        instance._previous_payment_id = None

@receiver(post_save, sender=Order)
def send_commission_to_influencer(sender, instance, **kwargs):
    if instance.influencer_code and instance.payment_id:
        # Check if payment_id was updated and if no commission has been credited for this order yet
        if (hasattr(instance, '_previous_payment_id') and
                instance.payment_id != instance._previous_payment_id):
            try:
                influencer = Influencer.objects.get(code=instance.influencer_code)
                commission_amount = (float(instance.total_price) * float(influencer.commission)) / 100  # assuming commission is a percentage

                # Check if this payment_id has been processed before
                if not InfluencerAmount.objects.filter(order__payment_id=instance.payment_id).exists():
                    # Create a new InfluencerAmount record
                    InfluencerAmount.objects.create(
                        influencer=influencer,
                        order=instance,
                        amount=commission_amount
                    )
            except Influencer.DoesNotExist:
                pass


class InfluencerLink(models.Model):
    influencer_code = models.CharField(max_length=20)
    ip_address = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.influencer_code

class InfluencerRecord(models.Model):
    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="influencer_records"
    )

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    benefit_percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100),
        ],
        help_text="Percentage benefit (0–100)"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.phone_number} ({self.benefit_percentage}%)"

ecomApp/templates/backend/advertisement_list.html
 {% include 'backend/header.html' %}
   {% include 'backend/sidebar.html' %}


 {% load static %}
  <!-- Content Wrapper. Contains page content -->
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?= $page_title;?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
<!--              <li class="breadcrumb-item"><a href="#">Home</a></li>-->
<!--              <li class="breadcrumb-item active"><?= $page_title;?></li>-->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

      <div class="container-fluid">

    <div class="">
        <div class="table-wrapper">
              <div class="col-12 ">
                <a href="{%  url 'add_advertisement' %}"><button class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Add  </button></a>

              </div>
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Advertisement Management<b> Table</b></h2></div>

                </div>
            </div>

           <table id="example1" class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th>Sl No</th>
                        <th>Photo</th>

            <th>Name</th>
            <th>Description</th>
            <th>Category</th>
                        <th>Status</th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ forloop.counter }}</td>
             <td>
                {% if item.add_photo %}
                <img src="{{ item.add_photo.url }}" alt="Add Image" width="60" height="30">
                {% else %}
        <img src=" {%  static 'assets/images/Frozenwala logo.png' %} " alt="Image" width="60" height="30"
                {% endif %}
            </td>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>

            </td>



<!--            <td>{{ item.category.name }}</td>-->
            <td>Home Page</td>
             <td>
                {% if item.status == True %}
                <a href="{% url 'deactivate_add' item.id %}" class="btn btn-sm btn-danger text-white">Deactivate</a>
                {% else %}
                <a href="{% url 'activate_add' item.id %}" class="btn btn-sm btn-success text-white">Activate</a>
                {% endif %}
            </td>
            <td>
                <a href="{% url 'edit_add' item.id %}" class="edit" title="Edit" data-toggle="tooltip"><i style="color: #ff9900;" class="fa fa-edit"></i></a>
                <a href="{% url 'view_add' item.id %}" class="view" title="View" data-toggle="tooltip"><i style="color: #ff9900;" class="fa fa-eye"></i></a>
                <a href="{% url 'delete_add' item.id %}"><i style="color: #ff9900;" class="fa fa-trash"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


        </div>
    </div>
</div>
    <!-- /.content-header -->

    <!-- Main content -->

      <!-- /.content -->
  </div>
{% include 'backend/footer.html' %}

  <!-- /.navbar -->

ecomApp/templates/backend/allinventory_list.html
  <!-- /.navbar -->
 {% include 'backend/header.html' %}
   {% include 'backend/sidebar.html' %}


 {% load static %}
 <style>
    .success-message {
        color: green;
        font-weight: bold;
        border: 1px solid green;
        padding: 10px;
        margin: 10px 0;
        background-color: #dff0d8; /* Optional background color */
    }
</style>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
   <section class="content">
    <div class="container-fluid">
        <div class="row">
            {% if message %}
    <ul class="messages">
            <p  class="alert-danger">{{ message }}</p>
    </ul>
{% endif %}
            <div class="col-md-12">
                <div class="card card-info">
                    <div class="card-header">
                        <h3 class="card-title">Edit Inventory</h3>
                    </div>
                    <div class="card-body">
    <form method="post" action="{% url 'update_all_stock' %}">
        {% csrf_token %}

                        {% for item in banform %}

            <div class="row">
                <div class="col-lg-4">
                                    <label for="title">Item Name:</label>
                                    <input type="text" id="title"  value="{{ item.item_id.title }}"name="title" maxlength="255" readonly class="form-control">
                                </div>
                                <div class="col-lg-4">
                                    <label for="title">Present Stock:</label>
                                    <input type="text" id="title"  value="{{ item.openingstock }}" maxlength="255" readonly class="form-control">
                                </div>
                                <div class="col-lg-4">
                                    <label for="description">Add Stock:</label>
                                    <input type="text" id="description"  value="" name="openingstock_{{ item.id }}"  class="form-control">
                                </div>

                            </div>
                        {% endfor %}

 <div class="mt-4">
                                <button type="submit" class="btn btn-primary">Update Item</button>
                                <a href="{% url 'stock' %}" class="btn btn-danger">Back</a>
                            </div>    </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



    <!-- /.content -->
  </div>


    <!-- Main conten
{% include 'backend/footer.html' %}

ecomApp/templates/backend/delivery_slots_add.html
{% include 'backend/header.html' %}
{% include 'backend/sidebar.html' %}
{% load static %}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-info">
                        <div class="card-header">
                            <h3 class="card-title">Add Delivery Slot</h3>
                        </div>

                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert 
                                        {% if message.tags == 'success' %}alert-success
                                        {% elif message.tags == 'error' %}alert-danger
                                        {% elif message.tags == 'warning' %}alert-warning
                                        {% else %}alert-info{% endif %}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}

                            <form method="POST">
                                {% csrf_token %}

                                <div class="row">

                                    <!-- Start Time -->
                                    <div class="col-lg-4">
                                        <label>Start Time</label>
                                        <input 
                                            type="time" 
                                            name="start_time" 
                                            class="form-control" 
                                            required>
                                    </div>

                                    <!-- End Time -->
                                    <div class="col-lg-4">
                                        <label>End Time</label>
                                        <input 
                                            type="time" 
                                            name="end_time" 
                                            class="form-control" 
                                            required>
                                    </div>

                                    <!-- Max Orders -->
                                    <div class="col-lg-4">
                                        <label>Max Orders</label>
                                        <input 
                                            type="number" 
                                            name="max_orders" 
                                            class="form-control" 
                                            min="1"
                                            value="10"
                                            required>
                                    </div>

                                    <!-- Active -->
                                    <div class="col-lg-12 mt-3">
                                        <div class="form-check">
                                            <input 
                                                type="checkbox" 
                                                name="is_active" 
                                                class="form-check-input" 
                                                id="is_active" 
                                                checked>
                                            <label class="form-check-label" for="is_active">
                                                Active
                                            </label>
                                        </div>
                                    </div>

                                    <!-- Buttons -->
                                    <div class="col-lg-12 mt-4">
                                        <button type="submit" class="btn btn-primary">
                                            Add Delivery Slot
                                        </button>
                                        <a href="{% url 'delivery_slots' %}" class="btn btn-danger">
                                            Back
                                        </a>
                                    </div>

                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

ecomApp/templates/backend/payment_options.html
 {% include 'backend/header.html' %}
   {% include 'backend/sidebar.html' %}


 {% load static %}
  <!-- Content Wrapper. Contains page content -->
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><?= $page_title;?></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
<!--              <li class="breadcrumb-item"><a href="#">Home</a></li>-->
<!--              <li class="breadcrumb-item active"><?= $page_title;?></li>-->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

       <div class="container-fluid">

    <div class="">
        <div class="table-wrapper">
             <div class="col-12 ">
                <a href="{%  url 'payment_options_add' %}"><button class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Add  </button></a>

              </div>
            {% if messages %}
              {% for message in messages %}
                  <div class="alert 
                      {% if message.tags == 'success' %}alert-success
                      {% elif message.tags == 'error' %}alert-danger
                      {% elif message.tags == 'warning' %}alert-warning
                      {% else %}alert-info{% endif %}">
                      {{ message }}
                  </div>
              {% endfor %}
            {% endif %}
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Payment Option <b>Details</b></h2></div>

                </div>
            </div>

            <table id="example1" class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Sl No</th>
                        <th>Type</th>
                        <th>Is Active</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for option in payment_options %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{option.get_code_display }}</td>
                        <td>
                          {% if option.is_active %}
                              Active
                          {% else %}
                              Inactive
                          {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'edit_payment_option' option.id %}" class="edit" title="Edit" data-toggle="tooltip"><i class="fa fa-edit"></i></a>
                            <a href="{% url 'delete_payment_option' option.id %}" ><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                {% endfor %}



                </tbody>
            </table>

        </div>
    </div>
</div>
    <!-- /.content-header -->

    <!-- Main content -->

      <!-- /.content -->
  </div>
{% include 'backend/footer.html' %}

  <!-- /.navbar -->